VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "AFcsJob"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Some commands

'    Dim Power As Double
'    starts with 1 this is the acquisition power
'    Power = FcsControl.BeamPathParameters.AttenuatorPower(2)
'    Power = FcsControl.BeamPathParameters.BleachAttenuatorPower(1)
'    FcsControl.BeamPathParameters.AttenuatorOn(1) = False
'    Dim FcsControl As AimFcsController
'    Set FcsControl = Fcs
'    ZEN.GUI.Fcs.LightPath.BleachLasers.ByIndex = 1
'    ZEN.GUI.Fcs.LightPath.BleachLasers.Transmission.Value = 0.1
